#:schema node_modules/wrangler/config-schema.json
name = "fry69-demo-placeholder"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
routes = [
	{ pattern = "*fry69.dev/demo/cloudflare-worker-placeholder*", zone_name = "fry69.dev" }
]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
